# """Add avatar_url and is_active to Student model

# Revision ID: 22cffd8c2fd8
# Revises: add_student_answers
# Create Date: 2025-06-17 05:16:13.068776

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '22cffd8c2fd8'
# down_revision = 'add_student_answers'
# branch_labels = None
# depends_on = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('students', sa.Column('avatar_url', sa.String(length=500), nullable=True))
#     op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
#     op.add_column('students', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('students', 'updated_at')
#     op.drop_column('students', 'is_active')
#     op.drop_column('students', 'avatar_url')
#     # ### end Alembic commands ###